### ISSUE TITLE
Time taken to finish runIROS.py on ordinary laptop without GPU

### ISSUE THREAD

**Issue by SKWH8140** [yuriautsumi/CultureNet-Autism#1]
I've been running runIROS.py for 27 hours and counting on ordinary laptop (intel core i7 5500u cpu @ 2.4 GHz).

How long would it take to finish running runIROS.py on this laptop?

**Comment by yuriautsumi** [comment]
Hi, could you provide information on what dataset you are running on? 

On our dataset, it takes ~48 hours on a standard laptop without GPU (2.7 GHz Intel Core i5).

**Comment by SKWH8140** [comment]
I'm running on your dataset provided by my Prof: data_0.pkl and data_1.pkl.

Just wanted to know if it's worth it to let it run or if it was being run properly. Anyway, it shut down halfway due to windows update while I was away.

Will have access to university's gpu computer soon.

**Comment by yuriautsumi** [comment]
If it helps, you could also modify the loop so that you save results after each loop iteration through a target child. If your computer shuts down, restart from the last save.

**Comment by SKWH8140** [comment]
Thanks. Haven't got to that stage yet but will try in future.
